# Generated by Django 2.2.14 on 2020-07-21 17:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 7, 21, 17, 13, 23, 222257, tzinfo=utc))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auser', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ManyToManyField(db_table='Vote_User', null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
