# Generated by Django 2.2.14 on 2020-07-21 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 19, 36, 24, 335137, tzinfo=utc)),
        ),
    ]
