# Generated by Django 2.2.14 on 2020-07-21 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200721_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_created=django.utils.timezone.now),
        ),
    ]
