# Generated by Django 2.2.14 on 2020-07-21 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20200721_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='vote',
            field=models.ManyToManyField(db_table='Vote_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
